services:
  vitest:
    build:
      context: ../apps/frontend
    image: nb-vitest
    volumes:
      - ../apps/frontend:/app
      - /app/node_modules
      - ./report:/report
    working_dir: /app
    command: npm run test:report
