import type { LocalizedDocsPage } from "./types";

// Scenario 1: verification of the demo app. Unlike the other scenarios it does not switch on a module;
// it runs the repository's test tools against the running apps stack. Structure, in both locales:
// an overview, then one section per test tool with "how to check the result" and "evaluation"
// subsections, then a cleanup section - the same closing every scenario page has.
export const scenarioTesting: LocalizedDocsPage = {
  en: {
    title: "Scenario 1: Verify the demo app",
    description:
      "This scenario verifies the operation of the demo application - the apps stack - with the test tools in " +
      "this repository: unit, end-to-end, contract, load and security. Each tool has its own make command and " +
      "produces an HTML report. The screenshots on this page are reports generated by these commands against " +
      "this repository.",
    sections: [
      {
        heading: "Overview",
        body: [
          "The same running apps stack is verified from several angles, each by a separate open-source tool. " +
            "For each tool, this page describes how to check its results and how those results are evaluated.",
          "shared/openapi/openapi.yaml is maintained by hand rather than generated from the code, so it can diverge " +
            "from the implementation, which is what makes checking it worthwhile. Specmatic verifies the provider " +
            "side (the real backend answers as the contract specifies) and serves a mock for the consumer side " +
            "(the frontend's calls are made against a mock built from the same file, with no real backend). " +
            "Kong can route the frontend to that mock without a " +
            "frontend change ([Scenario 2](/docs/scenario-kong)); agentgateway builds its MCP tools from the same " +
            "file ([Scenario 6](/docs/scenario-agentgateway)).",
          "Every test command leaves an HTML report (git-ignored, regenerated on each run). Open the file " +
            "directly in a browser, or serve its folder with python3 -m http.server.",
        ],
        table: {
          headers: ["Layer", "Tool", "What it checks"],
          nowrapColumns: [0, 1],
          rows: [
            ["Unit (backend)", "pytest", "Accounts and balances, password login, profile, JWT authentication (every route needs a token; expired, forged and tampered tokens are refused), Keycloak JWT validation, the MCP login. Uses an in-memory database."],
            ["Unit (frontend)", "Vitest", "The API client (including the bearer token it sends), the OIDC PKCE flow, and the rendering and order of these docs pages."],
            ["End to end", "Playwright", "In a real browser: login and logout, profile, a wrong password, the /en and /ja language routing."],
            ["Contract (provider)", "Specmatic", "Does the real backend honour openapi.yaml? Every path, method and response code is covered, the 401 of each protected route included."],
            ["Contract (consumer)", "Vitest + Specmatic mock", "Does the frontend's own API usage hold up against a mock built from the same contract?"],
            ["Load", "Locust", "HTTP, GraphQL and MySQL scenarios, an overload scenario, and the same overload sent through Kafka."],
            ["Security", "OWASP ZAP", "A passive scan of the frontend, an active scan, and an OpenAPI-driven scan of every backend route."],
          ],
        },
        closing: [
          "The unit tests require no running services and can be run first: make pytest:test and " +
          "make vitest:test. make all:test runs pytest, Vitest, Playwright and Specmatic in sequence, starting " +
          "the apps stack beforehand; the load test (make locust:load) and ZAP are not part of it - a sustained load run " +
          "and attack payloads are run explicitly. On GitHub, CI runs static checks only - Python lint, Dockerfile lint and " +
          "build, shell syntax, frontend type check and compose validation. The tests on this page require the " +
          "running stack and are run locally.",
        ],
      },
      {
        heading: "1. pytest: backend unit tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "pytest replaces MySQL with an in-memory database, so it needs no other service and completes in " +
                "under a second. The report is a single self-contained file: pytest/report/report.html.",
            ],
            code: [{ code: "make pytest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-pytest.png",
                alt: "pytest-html report: an environment table and a summary listing the backend tests, all passed",
                caption: "pytest: one self-contained report.html with the environment and a pass/fail row per test.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All tests pass. They cover accounts and balances, password login, the profile, JWT authentication - " +
                "test_auth_required.py asserts that every protected route answers 401 without a token - and Keycloak JWT " +
                "validation, including forged and tampered tokens.",
            ],
          },
        ],
      },
      {
        heading: "2. Vitest: frontend unit tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Vitest tests the frontend's logic without a browser: the API client, the PKCE handling of the login " +
                "redirect, and the server-side resolver that selects the backend to forward to. It replaces fetch, " +
                "so apps:up is not needed. The report is vitest/report/index.html.",
            ],
            code: [{ code: "make vitest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-vitest.png",
                alt: "Vitest HTML report: all tests passed, none failed, with the test tree grouped by file on the left",
                caption: "Vitest: a pass/fail dashboard and a browsable tree of every test, grouped by file.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All tests pass, with no failures. They cover the API client, including the bearer token it sends, the OIDC " +
                "PKCE flow, and the rendering and order of the docs pages.",
            ],
          },
        ],
      },
      {
        heading: "3. Playwright: end-to-end tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Playwright drives the real frontend in a browser against the real backend and MySQL, so the apps " +
                "stack must be running. The report is playwright/report/index.html; for a failed test, the trace " +
                "(screenshots, network and console) is available from the report.",
            ],
            code: [{ code: "make apps:up\nmake playwright:test" }],
            images: [
              {
                src: "/docs/screenshots/report-playwright.png",
                alt: "Playwright HTML report listing the end-to-end tests as passed, with durations",
                caption: "Playwright: one row per test with its duration.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "All tests pass in a real browser: login and logout, the profile, a wrong password, and the " +
                "language routing (/en, /ja).",
            ],
          },
        ],
      },
      {
        heading: "4. Specmatic: contract tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Specmatic reads shared/openapi/openapi.yaml and sends requests to the running backend (run make apps:up first), then reports coverage per " +
                "path, method and response code, including the error responses (401, 404, 422) that the normal " +
                "flow does not reach. The report is specmatic/report/test/html/index.html (HTML and JUnit files).",
              "The consumer side is checked against a mock built from the same contract: the frontend's own API " +
                "calls run against it; the mock reads the contract and examples from shared/openapi, so only the mock needs to be " +
                "started (not the apps stack). The tests compare complete response values and error bodies. " +
                "Its report is vitest/report-contract/index.html.",
            ],
            code: [
              { label: "Provider", code: "make apps:up\nmake specmatic:test" },
              { label: "Consumer", code: "make specmatic:mock-up\nmake vitest:contract-test" },
            ],
            images: [
              {
                src: "/docs/screenshots/report-specmatic.png",
                alt: "Specmatic contract test results: 100% API coverage, every scenario a success, and a table of every path, method and response code marked Covered",
                caption: "Specmatic: every scenario passed, 100% API coverage, broken down by path, method and response code.",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "Every scenario passes, and 100% of paths, methods and response codes are covered. The scenarios are " +
                "the requests built from the contract plus the examples checked in next to it (shared/openapi/examples), " +
                "so the error cases - the 401 of each protected route among them - and the authenticated calls are exercised as well.",
            ],
          },
        ],
        noteTitle: "Specmatic: external examples",
        noteHref: "https://docs.specmatic.io/features/external_examples",
        note:
          "shared/openapi/examples/*.json are Specmatic's externalized examples, passed in with --examples: the same " +
          "files supply the requests of the contract tests and the answers of the mock, which is why the mock " +
          "returns the same data every time.",
      },
      {
        heading: "5. Locust: load tests",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Locust runs against the running apps stack (make apps:up first) and reports response times and failures per endpoint. The available scenarios are HTTP, GraphQL " +
                "and MySQL, an overload scenario, and the same overload sent through Kafka; [Scenario 3](/docs/scenario-kafka) " +
                "and [Scenario 7](/docs/scenario-observability) use it to show the effect of an overload and how " +
                "Kafka and observability each respond. The report is locust/logs/<timestamp>/report.html. " +
                "make locust:load is a separate command from the test targets (and is not run by make all:test), since it puts sustained load on the stack.",
            ],
            code: [{ code: "make apps:up\nmake locust:load LOCUST_FILE=locustfile_http.py LOCUST_USERS=10 LOCUST_SPAWN_RATE=5 LOCUST_RUN_TIME=20s" }],
            images: [
              {
                src: "/docs/screenshots/report-locust.png",
                alt: "Locust test report: a short run of locustfile_http.py against http://backend:8080 with no failures, and response time percentiles per endpoint",
                caption: "Locust: request statistics and response-time percentiles per endpoint (a short 10-user, 30-second run with no failures).",
              },
            ],
          },
          {
            heading: "Evaluation",
            body: [
              "The sample run (10 users, 30 seconds, locustfile_http.py against the backend) completed " +
                "with no failures. The report gives the request statistics and the response-time percentiles for " +
                "each endpoint.",
            ],
          },
        ],
      },
      {
        heading: "6. OWASP ZAP: security scans",
        subsections: [
          {
            heading: "Checking the results",
            body: [
              "Both scans need the apps stack running (make apps:up first). make zap:baseline runs a passive scan of the frontend. make zap:api-scan runs an OpenAPI-driven scan " +
                "that sends real attack payloads to every backend route, so it only ever targets the apps stack. " +
                "Each scan writes zap/report/<scan>-report.html. " +
                "Note that zap:api-scan (and zap:full-scan) actually register their attack payloads as data: the scan logs in and posts to POST /transactions, so the Balances table fills with junk account names " +
                "(SQL injection strings, script snippets and the like). This is expected - run make apps:reset and make apps:up afterwards to get back to a clean demo state. " +
                "zap:baseline only observes and writes nothing.",
            ],
            code: [{ code: "make apps:up\nmake zap:baseline\nmake zap:api-scan\n\n# the scan leaves attack payloads in the database - wipe them afterwards\nmake apps:reset\nmake apps:up" }],
            images: [
              {
                src: "/docs/screenshots/report-zap.png",
                alt: "ZAP scanning report for http://backend:8080: a summary of alerts with no High or Medium ones, and insights about the endpoints it reached",
                caption: "ZAP api-scan of the backend: no High or Medium alerts. The scan logs in first, so its requests reach the protected routes.",
              },
            ],
            closing: ["There's also make zap:full-scan, a deeper active scan of the frontend itself - deliberately left out of the walkthrough above. Its attack payloads against the frontend's many hashed _next/static/* asset URLs can drive the Next.js dev server (Turbopack) into a CPU-pinning recompile loop that doesn't recover on its own, even after the scan stops. If that happens, restart just the frontend: docker compose -p apps -f apps/docker-compose.yml restart frontend."],
          },
          {
            heading: "Evaluation",
            body: [
              "The api-scan of the backend raised no High or Medium alerts and no failures. It logs in first and sends the " +
                "token with every request (zap/hooks/bearer_token.py), so the active rules reach the protected routes - " +
                "without it nearly every request would be a 401. That is how it found a real bug: a transaction name longer " +
                "than its column was a 500 (now a 422).",
              "The baseline scan of the frontend, a Next.js development server that is not hardened, raised warnings, " +
                "mostly missing security headers, with no failures.",
            ],
            closing: ["These are results from a development stack. They demonstrate the tooling and are not a security audit."],
          },
        ],
      },
      {
        heading: "Cleanup",
        body: [
          "Stop the services started for the tests. The reports remain in each tool's report directory (git-ignored) " +
            "until they are regenerated.",
        ],
        code: [{ code: "make specmatic:mock-down\nmake apps:down" }],
      },
    ],
  },
  ja: {
    title: "シナリオ1: デモアプリの動作検証",
    description:
      "このシナリオでは、デモアプリケーション(appsスタック)の動作を、本リポジトリのテストツールで検証します。" +
      "ユニット・E2E・コントラクト・負荷・セキュリティの各テストは、それぞれ専用のmakeコマンドを持ち、" +
      "HTMLレポートを出力します。本ページのスクリーンショットは、これらのコマンドを本リポジトリに対して" +
      "実行して生成した実際のレポートです。",
    sections: [
      {
        heading: "概要",
        body: [
          "同じ稼働中のappsスタックを、それぞれ別のオープンソースのツールで、複数の観点から検証します。" +
            "本ページでは、ツールごとに、結果の確認方法と、その結果の評価を記載します。",
          "shared/openapi/openapi.yamlはコードから生成せず手で保守しているため、実装と食い違う可能性があり、" +
            "それが確認する意味を生みます。Specmaticはプロバイダー側(実際のbackendがコントラクトどおりに" +
            "応答するか)を検証し、コンシューマー側にはmockを提供します(frontendの呼び出しを、同じファイルから" +
            "作ったモックに対して行い、実際のbackendは使いません)。" +
            "Kongはfrontendを変更せずに、そのモックへ経路を切り替えられます([シナリオ2](/docs/scenario-kong))。" +
            "agentgatewayも、同じファイルからMCPツールを作ります([シナリオ6](/docs/scenario-agentgateway))。",
          "どのテストコマンドも、HTMLレポートを出力します(gitignore対象で、実行のたびに再生成されます)。" +
            "ファイルをブラウザで直接開くか、フォルダをpython3 -m http.serverで配信して参照します。",
        ],
        table: {
          headers: ["レイヤー", "ツール", "確認すること"],
          nowrapColumns: [0, 1],
          rows: [
            ["ユニット(backend)", "pytest", "口座と残高、パスワードログイン、プロフィール、JWT認証(APIはすべてトークン必須で、期限切れ・偽造・改ざんされたトークンは拒否される)、KeycloakのJWT検証、MCPログイン。インメモリDBを使う。"],
            ["ユニット(frontend)", "Vitest", "APIクライアント(送信するbearerトークンを含む)、OIDCのPKCEフロー、このドキュメントページの表示と並び順。"],
            ["E2E", "Playwright", "実ブラウザで: ログイン・ログアウト、プロフィール、誤ったパスワード、/enと/jaの言語ルーティング。"],
            ["コントラクト(プロバイダー)", "Specmatic", "実際のbackendがopenapi.yamlどおりに応答するか。全パス・メソッド・レスポンスコードをカバーし、保護された各ルートの401も含む。"],
            ["コントラクト(コンシューマー)", "Vitest + Specmaticのmock", "frontend自身のAPI利用が、同じコントラクトから作ったモックに対して成立するか。"],
            ["負荷", "Locust", "HTTP・GraphQL・MySQLのシナリオ、overloadシナリオ、同じ負荷をKafka経由にしたもの。"],
            ["セキュリティ", "OWASP ZAP", "frontendのパッシブスキャン、アクティブスキャン、backendの全ルートを対象にしたOpenAPI駆動のスキャン。"],
          ],
        },
        closing: [
          "ユニットテストは稼働中のサービスを必要とせず、最初に実行できます: make pytest:test と make vitest:test。" +
          "make all:test は、pytest・Vitest・Playwright・Specmaticを順に実行します(先にappsスタックを起動します)。" +
          "負荷テスト(make locust:load)とZAPは対象外です — 持続的な負荷や攻撃ペイロードは、明示的に実行します。" +
          "GitHubのCIが実行するのは静的チェック — Pythonのlint、Dockerfileのlintとビルド、シェルの構文、" +
          "frontendの型チェック、composeの検証 — のみです。本ページのテストは稼働中のスタックが必要なため、" +
          "ローカルで実行します。",
        ],
      },
      {
        heading: "1. pytest: backendのユニットテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "pytestはMySQLをインメモリDBに差し替えるため、ほかのサービスを必要とせず、1秒未満で完了します。" +
                "レポートは自己完結した1つのファイル pytest/report/report.html です。",
            ],
            code: [{ code: "make pytest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-pytest.png",
                alt: "pytest-htmlのレポート。環境情報の表と、すべてPassedになったbackendのテスト一覧",
                caption: "pytest: 自己完結した1つのreport.html。環境情報と、テストごとの合否の行。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "すべてのテストが成功しました。対象は、口座と残高、パスワードログイン、プロフィール、JWT認証" +
                "(test_auth_required.pyが、保護されたルートすべてがトークンなしで401を返すことを確かめます)、KeycloakのJWT検証" +
                "(偽造・改ざんされたトークンを含む)です。",
            ],
          },
        ],
      },
      {
        heading: "2. Vitest: frontendのユニットテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Vitestはブラウザなしでfrontendのロジックをテストします。対象は、APIクライアント、ログインの" +
                "リダイレクトにおけるPKCEの扱い、転送先のbackendを選ぶサーバー側のresolverです。" +
                "fetchを差し替えるため、apps:upは不要です。レポートは vitest/report/index.html です。",
            ],
            code: [{ code: "make vitest:test" }],
            images: [
              {
                src: "/docs/screenshots/report-vitest.png",
                alt: "VitestのHTMLレポート。すべてPassで、Failはなく、左にファイル別のテストツリーが表示されている",
                caption: "Vitest: 成功・失敗のダッシュボードと、ファイル別にまとまった全テストのツリー。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "すべてのテストが成功し、失敗はありません。対象は、APIクライアント(送信するbearerトークンを含む)、OIDCのPKCEフロー、" +
                "ドキュメントページの表示と並び順です。",
            ],
          },
        ],
      },
      {
        heading: "3. Playwright: E2Eテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Playwrightは、実際のfrontendをブラウザで動かし、実際のbackendとMySQLに対して操作するため、" +
                "appsスタックを起動しておく必要があります。レポートは playwright/report/index.html で、" +
                "失敗したテストについては、レポートからトレース(スクリーンショット・ネットワーク・コンソール)を" +
                "参照できます。",
            ],
            code: [{ code: "make apps:up\nmake playwright:test" }],
            images: [
              {
                src: "/docs/screenshots/report-playwright.png",
                alt: "PlaywrightのHTMLレポート。E2Eテストがすべてpassedで、所要時間とともに一覧されている",
                caption: "Playwright: テストごとに1行と所要時間。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "実ブラウザでのテストがすべて成功しました。対象は、ログイン・ログアウト、プロフィール、誤ったパスワード、" +
                "言語ルーティング(/en、/ja)です。",
            ],
          },
        ],
      },
      {
        heading: "4. Specmatic: コントラクトテスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Specmaticはshared/openapi/openapi.yamlを読み、稼働中のbackendへ(先にmake apps:up)リクエストを送って、パス・メソッド・レスポンスコード" +
                "ごとのカバレッジを報告します。正常系では届かないエラーレスポンス(401・404・422)も含みます。" +
                "レポートは specmatic/report/test/html/index.html です(HTMLとJUnitのファイル)。",
              "コンシューマー側は、同じコントラクトから作ったmockに対して、frontend自身のAPI呼び出しを実行して" +
                "確認します。mockはshared/openapiのコントラクトとexampleを読むため、mockだけ起動すれば足ります(appsスタックは不要)。" +
                "テストは、レスポンスの全値とエラーの本文を比較します。" +
                "レポートは vitest/report-contract/index.html です。",
            ],
            code: [
              { label: "プロバイダー", code: "make apps:up\nmake specmatic:test" },
              { label: "コンシューマー", code: "make specmatic:mock-up\nmake vitest:contract-test" },
            ],
            images: [
              {
                src: "/docs/screenshots/report-specmatic.png",
                alt: "Specmaticのコントラクトテスト結果。APIカバレッジ100%、すべてのシナリオが成功で、全パス・メソッド・レスポンスコードがCoveredの表",
                caption: "Specmatic: すべてのシナリオが成功、APIカバレッジ100%。パス・メソッド・レスポンスコード別の内訳付き。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "すべてのシナリオが成功し、パス・メソッド・レスポンスコードの100%をカバーしました。シナリオは、" +
                "コントラクトから作ったリクエストと、同じ場所(shared/openapi/examples)にチェックインしたexampleで構成されるため、" +
                "エラーケース(保護された各ルートの401を含む)と認証つきの呼び出しも実行されます。",
            ],
          },
        ],
        noteTitle: "Specmatic: 外部化されたexample",
        noteHref: "https://docs.specmatic.io/features/external_examples",
        note:
          "shared/openapi/examples/*.jsonはSpecmaticの外部化されたexampleで、--examplesで渡しています。同じファイルがコントラクトテストのリクエストとモックの応答の両方に使われるため、モックは毎回同じデータを返します。",
      },
      {
        heading: "5. Locust: 負荷テスト",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "Locustは、稼働中のappsスタック(先にmake apps:up)に対して実行し、エンドポイントごとの応答時間と失敗を報告します。用意されているシナリオは、HTTP・GraphQL・MySQL、" +
                "overloadシナリオ、同じ負荷をKafka経由にしたものです。[シナリオ3](/docs/scenario-kafka)と" +
                "[シナリオ7](/docs/scenario-observability)は、これを使って、過負荷が何を起こし、Kafkaとオブザーバビリティが" +
                "それぞれどう応えるかを示します。レポートは locust/logs/<タイムスタンプ>/report.html です。" +
                "make locust:load はtest系のターゲットとは別のコマンドで(make all:testでは実行されません)、スタックに持続的な負荷をかけるためです。",
            ],
            code: [{ code: "make apps:up\nmake locust:load LOCUST_FILE=locustfile_http.py LOCUST_USERS=10 LOCUST_SPAWN_RATE=5 LOCUST_RUN_TIME=20s" }],
            images: [
              {
                src: "/docs/screenshots/report-locust.png",
                alt: "Locustのテストレポート。http://backend:8080に対するlocustfile_http.pyの短い実行で、失敗なしと、エンドポイントごとの応答時間パーセンタイル",
                caption: "Locust: エンドポイントごとのリクエスト統計と応答時間のパーセンタイル(10ユーザー・30秒の短い実行、失敗なし)。",
              },
            ],
          },
          {
            heading: "評価結果",
            body: [
              "サンプルの実行(10ユーザー、30秒、backendに対するlocustfile_http.py)は、失敗なく" +
                "完了しました。レポートには、エンドポイントごとのリクエスト統計と応答時間のパーセンタイルが" +
                "示されます。",
            ],
          },
        ],
      },
      {
        heading: "6. OWASP ZAP: セキュリティスキャン",
        subsections: [
          {
            heading: "確認方法",
            body: [
              "どちらのスキャンも、稼働中のappsスタックが必要です(先にmake apps:up)。make zap:baselineは、frontendのパッシブスキャンを実行します。make zap:api-scanは、OpenAPI駆動の" +
                "スキャンで、backendの全ルートへ実際の攻撃ペイロードを送るため、対象は常にappsスタックだけです。" +
                "どちらのスキャンも zap/report/<スキャン名>-report.html を出力します。" +
                "なお、zap:api-scan(およびzap:full-scan)は攻撃ペイロードを実際にデータとして登録します。スキャンはログインしてPOST /transactionsへ送信するため、" +
                "勘定科目残高にSQLインジェクション文字列やスクリプト片などの不審な勘定科目名が並びます。これは想定された動作です。スキャン後は make apps:reset と make apps:up を実行して、デモの状態を初期化してください。" +
                "zap:baselineは観察のみで、データは登録されません。",
            ],
            code: [{ code: "make apps:up\nmake zap:baseline\nmake zap:api-scan\n\n# スキャンで攻撃ペイロードがDBに残るため、終わったら初期化する\nmake apps:reset\nmake apps:up" }],
            images: [
              {
                src: "/docs/screenshots/report-zap.png",
                alt: "http://backend:8080に対するZAPのスキャンレポート。HighとMediumのアラートはなく、到達したエンドポイントの統計が表示されている",
                caption: "backendのZAP api-scan: High・Mediumのアラートなし。先にログインするため、リクエストは保護されたルートまで届く。",
              },
            ],
            closing: ["make zap:full-scanというコマンドもあります。frontend自体に対するより踏み込んだアクティブスキャンですが、上記のウォークスルーからは意図的に外しています。frontendの大量のハッシュ付き _next/static/* アセットURLへの攻撃ペイロードが、Next.jsの開発サーバー(Turbopack)を再コンパイル/キャッシュ書き換えの無限ループに陥らせ、スキャンを止めた後もCPUが張り付いたまま回復しないことがあるためです。発生した場合は frontend コンテナだけを再起動してください: docker compose -p apps -f apps/docker-compose.yml restart frontend"],
          },
          {
            heading: "評価結果",
            body: [
              "backendのapi-scanは、HighとMediumのアラートも失敗もありませんでした。先にログインして、すべてのリクエストに" +
                "トークンを付けて(zap/hooks/bearer_token.py)送るので、アクティブなルールは保護されたルートまで届きます" +
                " — 付けないと、ほとんどのリクエストが401になります。実際にこれで、トランザクション名が列の長さを超えると" +
                "500になる不具合(現在は422)が見つかりました。",
              "frontend(強化されていないNext.jsの開発サーバー)のベースラインスキャンは、警告(多くはセキュリティヘッダーの" +
                "欠如)がありましたが、失敗はありませんでした。",
            ],
            closing: ["開発用スタックでの結果です。ツールの実演であり、セキュリティ監査ではありません。"],
          },
        ],
      },
      {
        heading: "環境のクリーンアップ",
        body: [
          "テストのために起動したサービスを停止します。レポートは、再生成されるまで各ツールのレポートディレクトリに" +
            "残ります(gitignore対象)。",
        ],
        code: [{ code: "make specmatic:mock-down\nmake apps:down" }],
      },
    ],
  },
};
