import type { LocalizedDocsPage } from "./types";

export const testing: LocalizedDocsPage = {
  en: {
    title: "Testing",
    description:
      "A reference architecture is only convincing if you can check that it works. The same running apps " +
      "stack is tested from every angle - unit, end-to-end, contract, load and security - each by a " +
      "separate open-source tool with its own make command and its own HTML report. The screenshots " +
      "below are real reports, generated by these commands against this repository.",
    sections: [
      {
        heading: "The layers at a glance",
        table: {
          headers: ["Layer", "Tool", "What it checks", "Needs apps:up?", "Command"],
          rows: [
            ["Unit (backend)", "pytest", "22 tests: accounts and balances, password login, profile, Keycloak JWT validation (including forged and tampered tokens). Uses an in-memory database.", "No", "make pytest:test"],
            ["Unit (frontend)", "Vitest", "20 tests: the API client, the OIDC PKCE flow, and the backend resolver (round robin, fallback to the next instance).", "No", "make vitest:test"],
            ["End to end", "Playwright", "9 tests in a real browser: login and logout, profile, a wrong password, the frontend server's resolver API.", "Yes", "make playwright:test"],
            ["Contract (provider)", "Specmatic", "18 scenarios: does the real backend honour openapi.yaml? 100% of paths, methods and response codes covered.", "Yes", "make specmatic:test"],
            ["Contract (consumer)", "Vitest + Specmatic stub", "Does the frontend's own API usage hold up against a mock built from the same contract?", "Yes, plus the stub", "make specmatic:stub-up, then make vitest:contract-test"],
            ["Load", "Locust", "HTTP, GraphQL and MySQL scenarios, an overload scenario, the same overload spread over several backends (Consul) and pushed through Kafka.", "Yes", "make locust:test LOCUST_FILE=..."],
            ["Security", "OWASP ZAP", "A passive scan of the frontend, an active scan, and an OpenAPI-driven scan of every backend route.", "Yes", "make zap:baseline, zap:api-scan"],
          ],
        },
        note:
          "The unit tests need nothing running, so they are the quickest to try: make pytest:test and " +
          "make vitest:test. make all:test runs pytest, Vitest, Playwright and Specmatic in sequence " +
          "(starting apps first). On GitHub, CI runs the static checks - Python lint, Dockerfile lint and " +
          "build, shell syntax, frontend type check and compose validation; the tests above need the " +
          "running stack, so they are run locally.",
      },
      {
        heading: "Contract-first: one file, checked from both sides",
        body: [
          "apps/backend/openapi.yaml is written by hand, not generated from the code, so it can " +
            "genuinely disagree with the implementation - which is what makes checking it worthwhile. " +
            "Specmatic checks the provider side (the real backend answers the way the contract says) and " +
            "serves a stub for the consumer side (the frontend's calls are made against a mock built from the " +
            "same file, no real backend involved). Microcks turns the same file into a second, independent " +
            "mock, and Kong can route the frontend to either mock without a frontend change (Scenario 1). " +
            "agentgateway builds its MCP tools from the same file (Scenario 7).",
        ],
      },
      {
        heading: "Sample reports",
        body: [
          "Every test command leaves a browsable HTML report behind (all gitignored, regenerated on each " +
            "run). Open the file directly in a browser - no server needed - or serve the folder with " +
            "python3 -m http.server. These are real captures from this repository.",
        ],
        table: {
          headers: ["Tool", "Report file"],
          rows: [
            ["pytest", "pytest/report/report.html"],
            ["Vitest", "vitest/report/index.html (contract test: vitest/report-contract/index.html)"],
            ["Playwright", "playwright/report/index.html"],
            ["Specmatic", "specmatic/report/html/index.html"],
            ["Locust", "locust/logs/<timestamp>/report.html"],
            ["ZAP", "zap/report/<scan>-report.html"],
          ],
        },
      },
      {
        heading: "Unit tests: pytest and Vitest",
        body: [
          "pytest swaps MySQL for an in-memory database, so it runs anywhere in under a second. Vitest " +
            "tests the frontend's logic without a browser - the API client, the login redirect's PKCE " +
            "handling, and the server-side resolver that chooses between a fixed address and Consul.",
        ],
        images: [
          {
            src: "/docs/screenshots/report-pytest.png",
            alt: "pytest-html report: an environment table and a summary listing the backend tests, all passed",
            caption: "pytest: one self-contained report.html - environment, then a pass/fail row per test.",
          },
          {
            src: "/docs/screenshots/report-vitest.png",
            alt: "Vitest HTML report: 20 passed, 0 failed, with the test tree of api.test.ts, oidc.test.ts and backendResolver.test.ts on the left",
            caption: "Vitest: a dashboard (20 passed) and a browsable tree of every test, grouped by file.",
          },
        ],
      },
      {
        heading: "End to end and contract: Playwright and Specmatic",
        body: [
          "Playwright drives the real frontend in a browser against the real backend and MySQL. Specmatic " +
            "reads openapi.yaml and sends real requests to the running backend, then reports coverage " +
            "per path, method and response code - including the error responses (401, 404, 422) that the " +
            "happy path never reaches.",
        ],
        images: [
          {
            src: "/docs/screenshots/report-playwright.png",
            alt: "Playwright HTML report listing the 9 end-to-end tests as passed, with durations",
            caption: "Playwright: one row per test with its duration; on a failure the trace (screenshots, network, console) is one click away.",
          },
          {
            src: "/docs/screenshots/report-specmatic.png",
            alt: "Specmatic contract test results: 100% API coverage, 18 successes, and a table of every path, method and response code marked Covered",
            caption: "Specmatic: 18 of 18 scenarios passed, 100% API coverage, broken down by path, method and response code.",
          },
        ],
      },
      {
        heading: "Load and security: Locust and ZAP",
        body: [
          "Locust reports response times and failures per endpoint; Scenarios 2, 3 and 4 " +
            "use it to show what an overload does and how Kafka, several backends and observability each " +
            "respond. ZAP scans for vulnerabilities: the OpenAPI-driven scan sends real attack payloads to " +
            "every backend route, so it only ever targets apps.",
        ],
        images: [
          {
            src: "/docs/screenshots/report-locust.png",
            alt: "Locust test report: a 20-second run of locustfile_http.py against http://backend:8080 with 97 requests, 0 failures, and response time percentiles per endpoint",
            caption: "Locust: request statistics and response-time percentiles per endpoint (a short 10-user, 20-second run: 97 requests, 0 failures).",
          },
          {
            src: "/docs/screenshots/report-zap.png",
            alt: "ZAP scanning report for http://backend:8080: no High or Medium alerts, 2 Low, 5 informational, 27 endpoints",
            caption: "ZAP api-scan of the backend: 27 endpoints, no High or Medium alerts (2 Low). The scan passed 116 rules with 0 failures and 2 warnings.",
          },
        ],
        note:
          "Real runs, on a development stack: the ZAP baseline scan of the frontend (a Next.js dev " +
          "server, not hardened) passed 52 rules and warned on 15, mostly missing security headers, with 0 " +
          "failures. Treat the results as a demonstration of the tooling, not as a security audit.",
      },
      {
        heading: "Run it yourself",
        code: [
          {
            code:
              "make apps:up\n" +
              "make pytest:test && make vitest:test      # nothing else needed\n" +
              "make playwright:test && make specmatic:test\n" +
              "make locust:test LOCUST_FILE=locustfile_http.py LOCUST_USERS=10 LOCUST_SPAWN_RATE=5 LOCUST_RUN_TIME=20s\n" +
              "make zap:api-scan",
          },
        ],
      },
    ],
  },
  ja: {
    title: "テスト",
    description:
      "リファレンスアーキテクチャは、動くことを確かめられて初めて説得力を持ちます。同じ稼働中のappsスタックを、" +
      "ユニット・E2E・コントラクト・負荷・セキュリティのあらゆる角度からテストします。それぞれ別のオープンソースの" +
      "ツールが、専用のmakeコマンドとHTMLレポートを持っています。以下のスクリーンショットは、このリポジトリに対して" +
      "これらのコマンドで実際に生成したレポートです。",
    sections: [
      {
        heading: "レイヤーの一覧",
        table: {
          headers: ["レイヤー", "ツール", "確認すること", "apps:upが必要?", "コマンド"],
          rows: [
            ["ユニット(backend)", "pytest", "22件: 口座と残高、パスワードログイン、プロフィール、KeycloakのJWT検証(偽造・改ざんトークンを含む)。インメモリDBを使う。", "不要", "make pytest:test"],
            ["ユニット(frontend)", "Vitest", "20件: APIクライアント、OIDCのPKCEフロー、backend resolver(ラウンドロビンと次のインスタンスへのフォールバック)。", "不要", "make vitest:test"],
            ["E2E", "Playwright", "実ブラウザで9件: ログイン・ログアウト、プロフィール、誤ったパスワード、frontendサーバーのresolver API。", "必要", "make playwright:test"],
            ["コントラクト(プロバイダー)", "Specmatic", "18シナリオ: 実際のbackendがopenapi.yamlどおりに応答するか。パス・メソッド・レスポンスコードの100%をカバー。", "必要", "make specmatic:test"],
            ["コントラクト(コンシューマー)", "Vitest + Specmaticのstub", "frontend自身のAPI利用が、同じコントラクトから作ったモックに対して成立するか。", "必要(+stub)", "make specmatic:stub-up のあと make vitest:contract-test"],
            ["負荷", "Locust", "HTTP・GraphQL・MySQLのシナリオ、overloadシナリオ、同じ負荷を複数backend(Consul)へ分散、Kafka経由にしたもの。", "必要", "make locust:test LOCUST_FILE=..."],
            ["セキュリティ", "OWASP ZAP", "frontendのパッシブスキャン、アクティブスキャン、backendの全ルートを対象にしたOpenAPI駆動のスキャン。", "必要", "make zap:baseline、zap:api-scan"],
          ],
        },
        note:
          "ユニットテストは何も起動せずに動くので、最初に試すのに最適です: make pytest:test と make vitest:test。" +
          "make all:test は、pytest・Vitest・Playwright・Specmaticを順に実行します(先にappsを起動します)。" +
          "GitHubのCIが実行するのは静的チェック — Pythonのlint、Dockerfileのlintとビルド、シェルの構文、" +
          "frontendの型チェック、composeの検証 — です。上記のテストは稼働中のスタックが必要なので、ローカルで実行します。",
      },
      {
        heading: "コントラクトファースト: 1つのファイルを両側から確認する",
        body: [
          "apps/backend/openapi.yamlはコードから生成せず手で書いているので、実装と食い違う可能性が本当にあり — それが、" +
            "確認する意味を生みます。Specmaticはプロバイダー側(実際のbackendがコントラクトどおりに応答するか)を" +
            "確認し、コンシューマー側にはstubを提供します(frontendの呼び出しを、同じファイルから作ったモックに対して" +
            "行い、実際のbackendは使いません)。Microcksは同じファイルから、もう1つの独立したモックを作り、" +
            "Kongはfrontendを変更せずに、どちらのモックへも経路を切り替えられます(シナリオ1)。agentgatewayも、" +
            "同じファイルからMCPツールを作ります(シナリオ7)。",
        ],
      },
      {
        heading: "サンプルレポート",
        body: [
          "どのテストコマンドも、ブラウザで開けるHTMLレポートを残します(すべてgitignore対象で、実行のたびに再生成されます)。" +
            "ファイルをブラウザで直接開くか(サーバー不要)、フォルダをpython3 -m http.serverで配信してください。" +
            "以下は、このリポジトリでの実際のキャプチャです。",
        ],
        table: {
          headers: ["ツール", "レポートファイル"],
          rows: [
            ["pytest", "pytest/report/report.html"],
            ["Vitest", "vitest/report/index.html(コントラクトテスト: vitest/report-contract/index.html)"],
            ["Playwright", "playwright/report/index.html"],
            ["Specmatic", "specmatic/report/html/index.html"],
            ["Locust", "locust/logs/<タイムスタンプ>/report.html"],
            ["ZAP", "zap/report/<スキャン名>-report.html"],
          ],
        },
      },
      {
        heading: "ユニットテスト: pytestとVitest",
        body: [
          "pytestはMySQLをインメモリDBに差し替えるので、どこでも1秒未満で動きます。Vitestはブラウザなしで" +
            "frontendのロジックをテストします — APIクライアント、ログインのリダイレクトにおけるPKCEの扱い、" +
            "固定アドレスとConsulを選ぶサーバー側のresolverです。",
        ],
        images: [
          {
            src: "/docs/screenshots/report-pytest.png",
            alt: "pytest-htmlのレポート。環境情報の表と、すべてPassedになったbackendのテスト一覧",
            caption: "pytest: 自己完結した1つのreport.html — 環境情報と、テストごとの合否の行。",
          },
          {
            src: "/docs/screenshots/report-vitest.png",
            alt: "VitestのHTMLレポート。20件Pass・0件Failで、左にapi.test.ts・oidc.test.ts・backendResolver.test.tsのテストツリーが表示されている",
            caption: "Vitest: ダッシュボード(20件Pass)と、ファイル別にまとまった全テストのツリー。",
          },
        ],
      },
      {
        heading: "E2Eとコントラクト: PlaywrightとSpecmatic",
        body: [
          "Playwrightは、実際のfrontendをブラウザで動かし、実際のbackendとMySQLに対して操作します。" +
            "Specmaticはopenapi.yamlを読み、稼働中のbackendへ実際のリクエストを送って、パス・メソッド・" +
            "レスポンスコードごとのカバレッジを報告します — 正常系では届かない、エラーレスポンス(401・404・422)も含みます。",
        ],
        images: [
          {
            src: "/docs/screenshots/report-playwright.png",
            alt: "PlaywrightのHTMLレポート。9件のE2Eテストがpassedで、所要時間とともに一覧されている",
            caption: "Playwright: テストごとに1行と所要時間。失敗時は、トレース(スクリーンショット・ネットワーク・コンソール)にワンクリックで入れます。",
          },
          {
            src: "/docs/screenshots/report-specmatic.png",
            alt: "Specmaticのコントラクトテスト結果。APIカバレッジ100%、成功18件で、全パス・メソッド・レスポンスコードがCoveredの表",
            caption: "Specmatic: 18シナリオ中18件が成功、APIカバレッジ100%。パス・メソッド・レスポンスコード別の内訳付き。",
          },
        ],
      },
      {
        heading: "負荷とセキュリティ: LocustとZAP",
        body: [
          "Locustはエンドポイントごとの応答時間と失敗を報告します。シナリオ2・3・4は、これを使って、過負荷が何を起こし、" +
            "Kafka・複数のbackend・オブザーバビリティがそれぞれどう応えるかを示します。ZAPは脆弱性をスキャンします: " +
            "OpenAPI駆動のスキャンは、backendの全ルートへ実際の攻撃ペイロードを送るため、対象は常にappsだけです。",
        ],
        images: [
          {
            src: "/docs/screenshots/report-locust.png",
            alt: "Locustのテストレポート。http://backend:8080に対するlocustfile_http.pyの20秒間の実行で、97リクエスト・失敗0件と、エンドポイントごとの応答時間パーセンタイル",
            caption: "Locust: エンドポイントごとのリクエスト統計と応答時間のパーセンタイル(10ユーザー・20秒の短い実行: 97リクエスト、失敗0件)。",
          },
          {
            src: "/docs/screenshots/report-zap.png",
            alt: "http://backend:8080に対するZAPのスキャンレポート。HighとMediumのアラートはなく、Lowが2件、Informationalが5件、エンドポイント数は27",
            caption: "backendのZAP api-scan: 27エンドポイントでHigh・Mediumのアラートなし(Lowが2件)。116ルールに合格し、失敗0件・警告2件。",
          },
        ],
        note:
          "開発用スタックでの実際の実行結果です。frontend(強化されていないNext.jsの開発サーバー)のZAPベースラインスキャンは、" +
          "52ルールに合格し、15件で警告(多くはセキュリティヘッダーの欠如)、失敗は0件でした。結果はツールの実演として" +
          "受け取ってください。セキュリティ監査ではありません。",
      },
      {
        heading: "自分で動かす",
        code: [
          {
            code:
              "make apps:up\n" +
              "make pytest:test && make vitest:test      # ほかには何も要らない\n" +
              "make playwright:test && make specmatic:test\n" +
              "make locust:test LOCUST_FILE=locustfile_http.py LOCUST_USERS=10 LOCUST_SPAWN_RATE=5 LOCUST_RUN_TIME=20s\n" +
              "make zap:api-scan",
          },
        ],
      },
    ],
  },
};
